name: med_intel
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.0.4
  http: ^1.1.0
  provider: ^6.0.5  # For state management (simple to start)
  dotted_border: ^2.0.0+2
  flutter_svg: ^2.0.7  # For icons
  firebase_core: ^2.24.2
  firebase_auth: ^4.12.0

  # Add these later when needed:
  # google_maps_flutter: ^2.2.6
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
